- name: Masker Bordir Dahlia
  desc: Masker kain bordir bunga dahlia, bordir manual tasikmalaya. Bahan Katun, 3 ply/lapis
  price: 20k
  image: https://cf.shopee.co.id/file/6549ebebfdff7f4355dc0398f5f5b9e2
  url: https://shopee.co.id/Masker-Bordir-Tasik-i.226754372.7253556909

- name: Masker Bordir Simawar
  desc: Masker kain Bordir Bunga Mawar, bordir manual tasik. Dengan bahan kain 100% katun 3 lapisan
  price: 20k
  image: https://cf.shopee.co.id/file/8beee9059f2728ffa401e9888064623e
  url: https://shopee.co.id/Masker-Bordir-Tasik-i.226754372.4657392882

- name: masker Bordir Setaman
  desc: masker Bordir dengan 3 lapisan, Bordir Juki, Tali Karet, HeadLoop & Earloop.
  price: 20k
  image: https://cf.shopee.co.id/file/7b1760ae16b5a427c4c9ff32f68a69e4
  url: https://shopee.co.id/Masker-Bordir-Bunga-setaman-i.226754372.4478534055

- name: Masker Bordir Ilalang
  desc: Masker Kain Bordir Ilalang, cantik dan nyaman dipakai. Bordir manual (JUKI) dengan bahan kain 100% katun 3 lapisan
  price: 20k
  image: https://cf.shopee.co.id/file/0031e5ba7ee62316a17ecbd36ec7bff6
  url: https://shopee.co.id/Masker-Bordir-RumpuLaut-i.226754372.6457391578
